name: JudgmentNight
version: '${project.version}'
main: me.piglinstudio.judgmentnight.JudgmentNight
api-version: '1.16'
commands:
    night:
      permission:
       startNight.permission
       stopNight.permission